#!/bin/bash

set -eE

if [[ ! -x env ]]; then
    python3 -m virtualenv env
fi

. env/bin/activate

#set -x

if (( $# > 0 )); then
    cmd=$1; shift
fi

if [[ $cmd = install ]]; then
    python3 -m pip install --upgrade pip
    python3 -m pip install -q -r requirements.txt
    exit
fi

if [[ $cmd == run ]]; then
    python3 $1
    exit
fi

python3 test.py
